-- https://programmers.co.kr/learn/courses/30/lessons/59042
SELECT ANIMAL_ID, NAME FROM ANIMAL_OUTS
WHERE ANIMAL_ID not in (SELECT ANIMAL_ID FROM ANIMAL_INS) ORDER BY ANIMAL_ID

-- LEFT JOIN
SELECT A.ANIMAL_ID, A.NAME FROM ANIMAL_OUTS A 
LEFT JOIN ANIMAL_INS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY B.ANIMAL_ID ASC

-- https://programmers.co.kr/learn/courses/30/lessons/59043
SELECT A.ANIMAL_ID, A.NAME FROM ANIMAL_INS A
INNER JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID 
where A.DATETIME > B.DATETIME
ORDER BY A.DATETIME